add logger
thenativeweb/limes pull request #277
Opened 2021-01-13 06:50 UTC by kusigit

Add logger to write exception to the standard output.

2021-01-16 08:30 UTC, goloroden commented
@kusigit Thanks for your PR – we did not yet have the time to look into it, but we will do that soon. Sorry for the delay.

2021-01-16 08:33 UTC, kusigit commented
Easy. There's no hurry.

2021-02-09 14:08 UTC, goloroden requested changes
Hey @kusigit 👋 

Sorry for the very long delay … finally we found the time to have a look at your changes. I've left a comment, could you please have a look at it?

Oh, and if you want to, would you mind adding yourself as a contributor to the `package.json` file?

Have a nice day,


Golo

2021-02-09 14:08 UTC, goloroden commented on lib/Limes.ts
> +              throw new Error(err.message);
Since we are inside a callback here, which is wrapped by `await new Promise`, we should not just throw here, but reject the promise. So, can you please revert this line, also with the previous error message, but in addition log the detailed error message using the newly introduced logger?

Besides, the lines following this line would also need to be changed to `return reject`, could you please be so kind to adjust this as well?

2021-02-10 06:21 UTC, kusigit commented on lib/Limes.ts
> +              throw new Error(err.message);
Thanks for your review. I changed the appropriate lines.

2021-02-10 06:41 UTC, goloroden approved these changes

2021-02-10 06:42 UTC, merged